/*
This compliant solution uses std::random_device to generate a random value for seeding the 
Mersenne Twister engine object. The values generated by std::random_device are 
nondeterministic random numbers when possible, relying on random number generation devices, 
such as /dev/random. When such a device is not available, std::random_device may employ a 
random number engine; however, the initial value generated should have sufficient randomness 
to serve as a seed value.
*/

#include <random>
#include <iostream>

void f()
{
    std::random_device dev;
    std::mt19937 engine(dev());

    for (int i = 0; i < 10; ++i)
    {
        std::cout << engine() << ", ";
    }
}